rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::MotorTestSingle -> motor_test_single
      - rmcs_core::controller::MotorTestSingleController -> motor_test_single_controller
      - rmcs_core::controller::pid::PidController -> velocity_pid_controller
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

motor_test_single:
  ros__parameters:
    board_serial: ""          

motor_test_single_controller:
  ros__parameters:
    fixed_velocity_enabled: false     #定速转动（调试）
    target_velocity: 20.0
    max_velocity: 50.0
    velocity_filter_cutoff: 100.0      # 速度反馈低通滤波截止频率
    filter_sampling_frequency: 1000.0  # 滤波采样频率

velocity_pid_controller:
  ros__parameters:
    setpoint: /test/motor/target_velocity     
    measurement: /test/motor/velocity  
    feedforward: 0.0
    control: /test/motor/control_torque         
    kp: 0.3               
    ki: 0.005             
    kd: 0.0               
    integral_min: -10.0   
    integral_max: 10.0    
    output_min: -50.0     
    output_max: 50.0      

value_broadcaster:
  ros__parameters:
    forward_list:
      - /test/motor/velocity
      - /test/motor/measured_velocity
      - /test/motor/target_velocity
      - /test/motor/velocity_error
      - /test/motor/control_torque
      - /test/motor/torque
      
